### ISSUE TITLE
BlackPWM/BlackPWM.cpp line 382

### ISSUE THREAD

**Issue by scottyjustknows** [yigityuce/BlackLib#3]
In BlackPWM/BlackPWM.cpp line 382, `dutyFile << static_cast<int64_t>(std::round((this->getNumericPeriodValue()) * (1.0 - (percantage/100))));`, round should not be in the std namespace, as it is a part of cmath I believe. 

Suggested fix: `dutyFile << static_cast<int64_t>(round((this->getNumericPeriodValue()) * (1.0 - (percantage/100))));`

---

`
../BlackPWM/BlackPWM.cpp:382:46: error: 'round' is not a member of 'std'
             dutyFile << static_cast<int64_t>(std::round((this->getNumericPeriodValue()) * (1.0 - (percantage/100))));
                                              ^
../BlackPWM/BlackPWM.cpp:382:46: note: suggested alternative:
In file included from /usr/lib/gcc/x86_64-pc-cygwin/4.9.2/include/c++/cmath:44:0,
from ../BlackPWM/BlackPWM.h:38,
                 from ../BlackPWM/BlackPWM.cpp:32:
/usr/include/math.h:282:15: note:   'round'
 extern double round _PARAMS((double));
               ^
`

**Comment by yigityuce** [comment]
Hi,

std::round() is a C++11 function. You must compile your code with "std=c++0x" flag for error free compilation. But you may right, i could write only "round". I will fix this on next release.

You can see more detail at the links below:
1) http://en.cppreference.com/w/cpp/numeric/math/round
2) http://stackoverflow.com/questions/12696764/round-is-not-a-member-of-std
