### ISSUE TITLE
Servos

### ISSUE THREAD

**Issue by awright424** [yigityuce/BlackLib#4]
Do you have any examples of using blacklib to control a servo? I have been able to get motor control going but I feel like I damaged a servo already and wanted to know if you could assist

**Comment by yigityuce** [comment]
Unfortunately i have not any example about servo. But i think you can find it Beagleboard wiki or blog posts.

**Comment by awright424** [comment]
https://www.linux.com/learn/tutorials/776799-servo-control-from-the-beaglebone-black

I have used this and other libraries to control servo before using the
beaglebone black. How would I go about doing the same thing using your
library?

**Comment by TuxLeon** [comment]
It's quite easy. Use a PWM output. Configure a frequency of 50Hz (20ms period time I suppose) and then set the duty cycle to 5% (1ms). That should move your servo to a mid position.  Then you may vary the duty cycle between 2.5% and 7.5% (depending on your servo) to move the servo position.

**Comment by awright424** [comment]
So if I understand you correctly, assuming my pwm object is myPWM then I
would need to set the duty cycle, myPwm.setDutyPercent(5);
myPwm.setPeriodTime(20000000, BlackLib::nanosecond); To initially have my
servo set to 90 degrees.

**Comment by yigityuce** [comment]
@awright424 

At this link it uses Beaglebone Black's P9_16 pwm pin. You can use 

BlackLib::BlackPWM  myPwm(BlackLib::P8_19);


root@beaglebone:# cd /sys/devices/ocp.3/pwm_test_P9_16.*
# echo 0 >run
# cat period 
500000
# cat duty 
0
# cat polarity 
1
# echo 0 > polarity 
# echo 20000000 > period 
# echo 1000000 > duty 
# echo 1 >run
# echo 2000000 > duty 
# echo 0 >run

**Comment by yigityuce** [comment]
@awright424 

At this link it uses Beaglebone Black's P9_16 pwm pin. You can use this code at class instantiation:

```
BlackLib::BlackPWM  myPwm(BlackLib::P9_16);
```

```
root@beaglebone:# cd /sys/devices/ocp.3/pwm_test_P9_16.*
# echo 0 >run
# cat period 
500000
# cat duty 
0
# cat polarity 
1
# echo 0 > polarity 
# echo 20000000 > period 
# echo 1000000 > duty 
# echo 1 >run
# echo 2000000 > duty 
# echo 0 >run
```

And these commands are equals these:

```
myPwm.setRunState(BlackLib::stop);
std::cout << myPwm.getNumericPeriodValue() << std::endl;
std::cout << myPwm.getNumericDutyValue() << std::endl;
std::cout << myPwm.getPolarityValue() << std::endl;
myPwm.setPolarity(BlackLib::straight);
myPwm.setPeriodTime(20000000);
myPwm.setSpaceRatioTime(1000000);
myPwm.setRunState(BlackLib::run);
myPwm.setSpaceRatioTime(2000000);
myPwm.setRunState(BlackLib::stop);
```
