### ISSUE TITLE
Question about Blacklib_thread

### ISSUE THREAD

**Issue by forwardkth** [yigityuce/BlackLib#6]
Hi Yigityuce,
I am using blacklib to build my own robot project. It works well.

But I have a question about the blacklib thread. This is my robot source code. 
https://github.com/forwardkth/BBRobot_VisualGDB/blob/master/BBLib_VisualGDB/BlackLib/examples/example_wifirobot.h
In the end of this code, I create  TCP receive threads to process the TCP order in the main loop. (There is no loop in TCP receive thread.)

My question is that do I need to mannually delete the threads pointers like "rev" ? And how?

If I do not need to do that, how do you manage this in Blacklib_thread class?
## Thanks and looking forward to your reply.

while (1) { 
 sock = accept(serverSocket, 
 (struct sockaddr_) &clientAddr, 
 (socklen_t_)&clientAddrSize); 

 char order[1]; 
 recv(sock, &order, 1, 0); 
 if (order[0] != NULL) { 
 TCP_receiver *rev = new TCP_receiver(sock, order[0],servoXY, servoZ, 
 laser_status, 
 servoxy_angle, 
 servoz_angle, 
 GPIO1_12, 
 GPIO1_13, 
 GPIO1_14, 
 GPIO1_15, 
 GPIO1_6); 
 rev->run(); 

}

}

Best Regards,

**Comment by yigityuce** [comment]
Hi @forwardkth ,

The TCP_receiver thread is created inside the block which wrapped with curly braces. In this code the thread will be stopped when the program reached the end of curly braces. So your onStartHandler function which belongs to TCP_receiver thread will be interrupted and terminated. You should wait the thread's execution with [waitUntilFinish() function](https://github.com/yigityuce/BlackLib/blob/master/v3_0/BlackThread/BlackThread.h#L745) or [WAIT_THREAD_FINISH() macro](https://github.com/yigityuce/BlackLib/blob/master/v3_0/BlackThread/BlackThread.h#L48) until it finished.

But in this case your program becomes to regular application, not a multi-task application. So you may want to change your approach. Maybe you can store TCP_receiver class pointers in an STL containers, track finished threads and remove them from container etc. or you can do tcp operations (recv,connect...) in the thread.

**Comment by forwardkth** [comment]
Hi @yigityuce,

Thank you very much for the explaination  :+1: 

Good suggestions, I also did another approch that putting the TCP operations totally in a thread. I will also try the STL container approach.

BR,

**Comment by forwardkth** [comment]
Hi @yigityuce,

In my original case, I put the creation of TCP_receiver threads in a "while(1)" loop. My idea is to create multithreads without waiting. Will the threads still be terminated when reach the  curly braces ?

If I call waitUntilFinish() function in the main loop, the main loop will have a pause where I call waitUntilFinish().

while(1)
{
................
TCP_receiver *rev = new TCP_receiver(sock, order[0],servoXY, servoZ, .......
rec - > run();
.................
}

If i am right, I think the good choice is just to  add the STL container for the thread pointers' management. According to your second approach. 

BR,

**Comment by yigityuce** [comment]
Hi @forwardkth ,

You can find an answer to your questions in [this link](http://stackoverflow.com/a/22146244/3217160). What happens to pointer in the scope after it goes out, is described fluently and simply.

**Comment by forwardkth** [comment]
Hi @yigityuce,

Thank you very much. I read the stackoverflow posts carefully. I think I choose a complex solution for a simple thing.

Now I put all the TCP communication in threads. So only 2 or 3 threads keep running at the same time.
.
This looks more clear. The threads pointers will be deleted when returning of isFinished()  is TRUE..

I also tried to figure out the std container solution. But I do not succeed. I will look into it later.

Thanks. :)

---

```
//start ultrasound thread
Ultrasound *ultras = new Ultrasound(Usound_serial, ultra_distance, lowlen, highlen);
ultras->run();

//start TCP_RX thread
TCP_receiver *rev = new TCP_receiver(servoXY, servoZ,
    laser_status,
    servoxy_angle,
    servoz_angle,
    GPIO1_12,
    GPIO1_13,
    GPIO1_14,
    GPIO1_15,
    GPIO1_6);
rev->run();

//start TCP_TX thread
//..................

//main loop
while(1) {

    usleep(100);
    if (ultras->isFinished()) {
        delete ultras;
        ultras = nullptr;
        break;
    } else if (rev->isFinished()) {
        delete rev;
        rev = nullptr;
        break;
    }
}
```

---

BR,

**Comment by yigityuce** [comment]
Your welcome @forwardkth
